### ISSUE TITLE
Chopping down a tree doesn't make the used tool lose its durability.

### ISSUE THREAD

**Issue by cobaltlol2** [PandaMods-Dev/Pandas-Falling-Trees#83] opened 2024-07-14 08:41 UTC

**Comment by makumaku1974** [comment] 2024-07-19 02:26
Also modded axe only uses 1 durability

**Comment by wendall911** [comment] 2024-08-12 15:56
For our modded axe, it is just a simple extension of vanilla AxeItem. So anything that extends vanilla will not use durability.

**Comment by cobaltlol2** [comment] 2024-08-13 20:38
> For our modded axe, it is just a simple extension of vanilla AxeItem. So anything that extends vanilla will not use durability.

It's still not fixed even by using the LMFT mod, I chopped 4 trees in this ss and yet my axe took 0 durability damage. 
![image](https://github.com/user-attachments/assets/50d934e9-8b4a-4959-aa8f-d122d96986f6)

**Comment by makumaku1974** [comment] 2024-08-14 01:46
> > For our modded axe, it is just a simple extension of vanilla AxeItem. So anything that extends vanilla will not use durability.
> 
> It's still not fixed even by using the LMFT mod, I chopped 4 trees in this ss and yet my axe took 0 durability damage. ![image](https://private-user-images.githubusercontent.com/174870492/357565500-50d934e9-8b4a-4959-aa8f-d122d96986f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDAyNTUsIm5iZiI6MTcyMzU5OTk1NSwicGF0aCI6Ii8xNzQ4NzA0OTIvMzU3NTY1NTAwLTUwZDkzNGU5LThiNGEtNDk1OS1hYThmLWQxMjJkOTY5ODZmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMTQ1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWQwOGJiMzFlNjBhMmZjYzk1YWY4NjcxZTA2NGViOWZhZjA4N2U4ZjVhZDM0Nzg2YzkyMmVjZWI2NTQyMWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.43eLowpIsNsIpXPae9vgu7if-hYLdxSe5orrU0DSpGs)

every axe is affected.

**Comment by MCRusher** [comment] 2024-08-14 05:23
> > For our modded axe, it is just a simple extension of vanilla AxeItem. So anything that extends vanilla will not use durability.
> 
> It's still not fixed even by using the LMFT mod, I chopped 4 trees in this ss and yet my axe took 0 durability damage. ![image](https://private-user-images.githubusercontent.com/174870492/357565500-50d934e9-8b4a-4959-aa8f-d122d96986f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTMxNDUsIm5iZiI6MTcyMzYxMjg0NSwicGF0aCI6Ii8xNzQ4NzA0OTIvMzU3NTY1NTAwLTUwZDkzNGU5LThiNGEtNDk1OS1hYThmLWQxMjJkOTY5ODZmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwNTIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWU5N2ZkNTE4NjIyZWNiZGE1OTRlNTRmMzRhNmFiNjUzYmM2NjlkZWRkMmM1NGQ4ODYyMjk2YmU2MzgzZTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dek2AhSLs2o76SlLWwRloV2wDFJOrs30JoJ1hqwfoEk)

Probably because that fix was for Dynamic Trees:

> Ok, and there is a bug in Dynamic Trees as well: https://github.com/DynamicTreesTeam/DynamicTrees/issues/894
> There is a workaround, you can install https://www.curseforge.com/minecraft/mc-mods/lmft and the issue is resolved. There was a bug in their tags and this mod works around the issue.

**Comment by MCRusher** [comment] 2024-08-14 05:30
I tried rolling the mod back to see if an old version would still work, in 0.12.3 axes seem to still work as intended.

**Comment by makumaku1974** [comment] 2024-08-14 06:32
> I tried rolling the mod back to see if an old version would still work, in 0.12.3 axes seem to still work as intended.

que version?

**Comment by MCRusher** [comment] 2024-08-14 17:41
I said what version in the comment lol, 0.12.3

**Comment by ThePandaOliver** [comment] 2024-08-26 21:00
Should be fixed

**Closed by ThePandaOliver** 2024-08-26 21:00 UTC
